### ISSUE TITLE
pass a reference to new subroutine in Jet.pm

### ISSUE THREAD

**Issue by yasu47b** [kazeburo/Redis-Jet#2]
Hello, Kazeburo.

I thought new subroutine in Jet.pm can accept a reference as an argument.

then I noticed that ref $_ should be $_[0]. 

thanks.

```
sub new {
    my $class = shift;
    my %args = ref $_ ? %{$_[0]} : @_;
    %args = (
```

**Comment by kazeburo** [comment]
merged #3  and released 0.06.
Thank you.
