### ISSUE TITLE
Connect to unix socket?

### ISSUE THREAD

**Issue by lumina7** [kazeburo/Redis-Jet#9]
Hello,

Thank you for Redis-Jet.
Redis can be configured to a unix socket, is it possible to implement something like this?

$jet->connect_unix( $path ) instead of hostname:port
or even
my $jet = Redis::Jet->new( server => '/run/redis/redis.sock' );

Unix socket are usually faster.
Thanks.

**Comment by lumina7** [comment]
a simple add...

my $sun = sockaddr_un($self->get_unix_socket);
socket(my $socket, PF_UNIX, SOCK_STREAM, 0);
connect($socket, $sun);

**Comment by kazeburo** [comment]
Supports unix_socket in https://github.com/kazeburo/Redis-Jet/pull/10.
